# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: index_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'index_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13index_service.proto\x12\x08indexsvc\"\x13\n\x11GetCentersRequest\"a\n\x12GetCentersResponse\x12\x13\n\x0b\x63\x65nters_sha\x18\x01 \x01(\t\x12\x14\n\x0c\x63\x65nters_path\x18\x02 \x01(\t\x12\x0b\n\x03\x64im\x18\x03 \x01(\r\x12\x13\n\x0bnum_centers\x18\x04 \x01(\r\"@\n\x1bGetClusterCandidatesRequest\x12\x12\n\ncluster_id\x18\x01 \x01(\r\x12\r\n\x05top_r\x18\x02 \x01(\r\">\n\tCandidate\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0f\n\x07pq_code\x18\x02 \x01(\x0c\x12\x14\n\x0c\x61pprox_score\x18\x03 \x01(\x02\"Z\n\x1cGetClusterCandidatesResponse\x12\'\n\ncandidates\x18\x01 \x03(\x0b\x32\x13.indexsvc.Candidate\x12\x11\n\tpadded_to\x18\x02 \x01(\r\"D\n\x17\x43reateDiagBlocksRequest\x12\x15\n\rcandidate_ids\x18\x01 \x03(\x04\x12\x12\n\npack_slots\x18\x02 \x01(\r\"k\n\x0f\x44iagBlockLayout\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\t\x12\x11\n\tmmap_path\x18\x02 \x01(\t\x12\r\n\x05slots\x18\x03 \x01(\r\x12\x0e\n\x06stride\x18\x04 \x01(\r\x12\x14\n\x0c\x64iag_offsets\x18\x05 \x03(\r\"E\n\x18\x43reateDiagBlocksResponse\x12)\n\x06\x62locks\x18\x01 \x03(\x0b\x32\x19.indexsvc.DiagBlockLayout2\x99\x02\n\x0cIndexService\x12G\n\nGetCenters\x12\x1b.indexsvc.GetCentersRequest\x1a\x1c.indexsvc.GetCentersResponse\x12\x65\n\x14GetClusterCandidates\x12%.indexsvc.GetClusterCandidatesRequest\x1a&.indexsvc.GetClusterCandidatesResponse\x12Y\n\x10\x43reateDiagBlocks\x12!.indexsvc.CreateDiagBlocksRequest\x1a\".indexsvc.CreateDiagBlocksResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'index_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETCENTERSREQUEST']._serialized_start=33
  _globals['_GETCENTERSREQUEST']._serialized_end=52
  _globals['_GETCENTERSRESPONSE']._serialized_start=54
  _globals['_GETCENTERSRESPONSE']._serialized_end=151
  _globals['_GETCLUSTERCANDIDATESREQUEST']._serialized_start=153
  _globals['_GETCLUSTERCANDIDATESREQUEST']._serialized_end=217
  _globals['_CANDIDATE']._serialized_start=219
  _globals['_CANDIDATE']._serialized_end=281
  _globals['_GETCLUSTERCANDIDATESRESPONSE']._serialized_start=283
  _globals['_GETCLUSTERCANDIDATESRESPONSE']._serialized_end=373
  _globals['_CREATEDIAGBLOCKSREQUEST']._serialized_start=375
  _globals['_CREATEDIAGBLOCKSREQUEST']._serialized_end=443
  _globals['_DIAGBLOCKLAYOUT']._serialized_start=445
  _globals['_DIAGBLOCKLAYOUT']._serialized_end=552
  _globals['_CREATEDIAGBLOCKSRESPONSE']._serialized_start=554
  _globals['_CREATEDIAGBLOCKSRESPONSE']._serialized_end=623
  _globals['_INDEXSERVICE']._serialized_start=626
  _globals['_INDEXSERVICE']._serialized_end=907
# @@protoc_insertion_point(module_scope)
