# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gateway.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gateway.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgateway.proto\x12\ngateway.v1\"\x97\x01\n\rSearchRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63luster_ids\x18\x02 \x03(\t\x12\x0c\n\x04\x63t_q\x18\x03 \x01(\x0c\x12\x0f\n\x07key_ver\x18\x04 \x01(\t\x12\x13\n\x0b\x66\x61ke_policy\x18\x05 \x01(\t\x12\r\n\x05scale\x18\x06 \x01(\x04\x12\x0c\n\x04topR\x18\x07 \x01(\r\x12\x0c\n\x04mode\x18\x08 \x01(\t\")\n\tPackShape\x12\r\n\x05\x62\x61tch\x18\x01 \x01(\r\x12\r\n\x05slots\x18\x02 \x01(\r\"l\n\x0eSearchResponse\x12\x1a\n\x12scores_ciphertexts\x18\x01 \x03(\x0c\x12*\n\x0bpack_shapes\x18\x02 \x03(\x0b\x32\x15.gateway.v1.PackShape\x12\x12\n\nlatency_ms\x18\x03 \x01(\r2Q\n\x0eGatewayService\x12?\n\x06Search\x12\x19.gateway.v1.SearchRequest\x1a\x1a.gateway.v1.SearchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gateway_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEARCHREQUEST']._serialized_start=30
  _globals['_SEARCHREQUEST']._serialized_end=181
  _globals['_PACKSHAPE']._serialized_start=183
  _globals['_PACKSHAPE']._serialized_end=224
  _globals['_SEARCHRESPONSE']._serialized_start=226
  _globals['_SEARCHRESPONSE']._serialized_end=334
  _globals['_GATEWAYSERVICE']._serialized_start=336
  _globals['_GATEWAYSERVICE']._serialized_end=417
# @@protoc_insertion_point(module_scope)
