# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import hecompute_pb2 as hecompute__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in hecompute_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HeComputeServiceStub(object):
    """======= Service =======

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EvalKeys = channel.unary_unary(
                '/hecompute.v1.HeComputeService/EvalKeys',
                request_serializer=hecompute__pb2.EvalKeysRequest.SerializeToString,
                response_deserializer=hecompute__pb2.EvalKeysReply.FromString,
                _registered_method=True)
        self.ScoreBatch = channel.unary_unary(
                '/hecompute.v1.HeComputeService/ScoreBatch',
                request_serializer=hecompute__pb2.ScoreBatchRequest.SerializeToString,
                response_deserializer=hecompute__pb2.ScoreBatchReply.FromString,
                _registered_method=True)


class HeComputeServiceServicer(object):
    """======= Service =======

    """

    def EvalKeys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScoreBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HeComputeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EvalKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.EvalKeys,
                    request_deserializer=hecompute__pb2.EvalKeysRequest.FromString,
                    response_serializer=hecompute__pb2.EvalKeysReply.SerializeToString,
            ),
            'ScoreBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.ScoreBatch,
                    request_deserializer=hecompute__pb2.ScoreBatchRequest.FromString,
                    response_serializer=hecompute__pb2.ScoreBatchReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hecompute.v1.HeComputeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hecompute.v1.HeComputeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HeComputeService(object):
    """======= Service =======

    """

    @staticmethod
    def EvalKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hecompute.v1.HeComputeService/EvalKeys',
            hecompute__pb2.EvalKeysRequest.SerializeToString,
            hecompute__pb2.EvalKeysReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScoreBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hecompute.v1.HeComputeService/ScoreBatch',
            hecompute__pb2.ScoreBatchRequest.SerializeToString,
            hecompute__pb2.ScoreBatchReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
