# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import index_service_pb2 as index__service__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in index_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IndexServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCenters = channel.unary_unary(
                '/indexsvc.IndexService/GetCenters',
                request_serializer=index__service__pb2.GetCentersRequest.SerializeToString,
                response_deserializer=index__service__pb2.GetCentersResponse.FromString,
                _registered_method=True)
        self.GetClusterCandidates = channel.unary_unary(
                '/indexsvc.IndexService/GetClusterCandidates',
                request_serializer=index__service__pb2.GetClusterCandidatesRequest.SerializeToString,
                response_deserializer=index__service__pb2.GetClusterCandidatesResponse.FromString,
                _registered_method=True)
        self.CreateDiagBlocks = channel.unary_unary(
                '/indexsvc.IndexService/CreateDiagBlocks',
                request_serializer=index__service__pb2.CreateDiagBlocksRequest.SerializeToString,
                response_deserializer=index__service__pb2.CreateDiagBlocksResponse.FromString,
                _registered_method=True)


class IndexServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCenters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClusterCandidates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateDiagBlocks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IndexServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCenters': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCenters,
                    request_deserializer=index__service__pb2.GetCentersRequest.FromString,
                    response_serializer=index__service__pb2.GetCentersResponse.SerializeToString,
            ),
            'GetClusterCandidates': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClusterCandidates,
                    request_deserializer=index__service__pb2.GetClusterCandidatesRequest.FromString,
                    response_serializer=index__service__pb2.GetClusterCandidatesResponse.SerializeToString,
            ),
            'CreateDiagBlocks': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDiagBlocks,
                    request_deserializer=index__service__pb2.CreateDiagBlocksRequest.FromString,
                    response_serializer=index__service__pb2.CreateDiagBlocksResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'indexsvc.IndexService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('indexsvc.IndexService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IndexService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCenters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/indexsvc.IndexService/GetCenters',
            index__service__pb2.GetCentersRequest.SerializeToString,
            index__service__pb2.GetCentersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetClusterCandidates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/indexsvc.IndexService/GetClusterCandidates',
            index__service__pb2.GetClusterCandidatesRequest.SerializeToString,
            index__service__pb2.GetClusterCandidatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateDiagBlocks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/indexsvc.IndexService/CreateDiagBlocks',
            index__service__pb2.CreateDiagBlocksRequest.SerializeToString,
            index__service__pb2.CreateDiagBlocksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
