// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: gateway.proto

#include "gateway.pb.h"
#include "gateway.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace gateway {
namespace v1 {

static const char* GatewayService_method_names[] = {
  "/gateway.v1.GatewayService/Search",
};

std::unique_ptr< GatewayService::Stub> GatewayService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< GatewayService::Stub> stub(new GatewayService::Stub(channel));
  return stub;
}

GatewayService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Search_(GatewayService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status GatewayService::Stub::Search(::grpc::ClientContext* context, const ::gateway::v1::SearchRequest& request, ::gateway::v1::SearchResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Search_, context, request, response);
}

void GatewayService::Stub::experimental_async::Search(::grpc::ClientContext* context, const ::gateway::v1::SearchRequest* request, ::gateway::v1::SearchResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Search_, context, request, response, std::move(f));
}

void GatewayService::Stub::experimental_async::Search(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::gateway::v1::SearchResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Search_, context, request, response, std::move(f));
}

void GatewayService::Stub::experimental_async::Search(::grpc::ClientContext* context, const ::gateway::v1::SearchRequest* request, ::gateway::v1::SearchResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Search_, context, request, response, reactor);
}

void GatewayService::Stub::experimental_async::Search(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::gateway::v1::SearchResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Search_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::gateway::v1::SearchResponse>* GatewayService::Stub::AsyncSearchRaw(::grpc::ClientContext* context, const ::gateway::v1::SearchRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::gateway::v1::SearchResponse>::Create(channel_.get(), cq, rpcmethod_Search_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::gateway::v1::SearchResponse>* GatewayService::Stub::PrepareAsyncSearchRaw(::grpc::ClientContext* context, const ::gateway::v1::SearchRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::gateway::v1::SearchResponse>::Create(channel_.get(), cq, rpcmethod_Search_, context, request, false);
}

GatewayService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GatewayService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GatewayService::Service, ::gateway::v1::SearchRequest, ::gateway::v1::SearchResponse>(
          [](GatewayService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::gateway::v1::SearchRequest* req,
             ::gateway::v1::SearchResponse* resp) {
               return service->Search(ctx, req, resp);
             }, this)));
}

GatewayService::Service::~Service() {
}

::grpc::Status GatewayService::Service::Search(::grpc::ServerContext* context, const ::gateway::v1::SearchRequest* request, ::gateway::v1::SearchResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace gateway
}  // namespace v1

