// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gateway.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_gateway_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_gateway_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_gateway_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_gateway_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_gateway_2eproto;
namespace gateway {
namespace v1 {
class PackShape;
class PackShapeDefaultTypeInternal;
extern PackShapeDefaultTypeInternal _PackShape_default_instance_;
class SearchRequest;
class SearchRequestDefaultTypeInternal;
extern SearchRequestDefaultTypeInternal _SearchRequest_default_instance_;
class SearchResponse;
class SearchResponseDefaultTypeInternal;
extern SearchResponseDefaultTypeInternal _SearchResponse_default_instance_;
}  // namespace v1
}  // namespace gateway
PROTOBUF_NAMESPACE_OPEN
template<> ::gateway::v1::PackShape* Arena::CreateMaybeMessage<::gateway::v1::PackShape>(Arena*);
template<> ::gateway::v1::SearchRequest* Arena::CreateMaybeMessage<::gateway::v1::SearchRequest>(Arena*);
template<> ::gateway::v1::SearchResponse* Arena::CreateMaybeMessage<::gateway::v1::SearchResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace gateway {
namespace v1 {

// ===================================================================

class SearchRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:gateway.v1.SearchRequest) */ {
 public:
  inline SearchRequest() : SearchRequest(nullptr) {};
  virtual ~SearchRequest();

  SearchRequest(const SearchRequest& from);
  SearchRequest(SearchRequest&& from) noexcept
    : SearchRequest() {
    *this = ::std::move(from);
  }

  inline SearchRequest& operator=(const SearchRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline SearchRequest& operator=(SearchRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SearchRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SearchRequest* internal_default_instance() {
    return reinterpret_cast<const SearchRequest*>(
               &_SearchRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SearchRequest& a, SearchRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(SearchRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SearchRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline SearchRequest* New() const final {
    return CreateMaybeMessage<SearchRequest>(nullptr);
  }

  SearchRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SearchRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SearchRequest& from);
  void MergeFrom(const SearchRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SearchRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "gateway.v1.SearchRequest";
  }
  protected:
  explicit SearchRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_gateway_2eproto);
    return ::descriptor_table_gateway_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kClusterIdsFieldNumber = 2,
    kSessionIdFieldNumber = 1,
    kCtQFieldNumber = 3,
    kKeyVerFieldNumber = 4,
    kFakePolicyFieldNumber = 5,
    kScaleFieldNumber = 6,
    kTopRFieldNumber = 7,
  };
  // repeated string cluster_ids = 2;
  int cluster_ids_size() const;
  private:
  int _internal_cluster_ids_size() const;
  public:
  void clear_cluster_ids();
  const std::string& cluster_ids(int index) const;
  std::string* mutable_cluster_ids(int index);
  void set_cluster_ids(int index, const std::string& value);
  void set_cluster_ids(int index, std::string&& value);
  void set_cluster_ids(int index, const char* value);
  void set_cluster_ids(int index, const char* value, size_t size);
  std::string* add_cluster_ids();
  void add_cluster_ids(const std::string& value);
  void add_cluster_ids(std::string&& value);
  void add_cluster_ids(const char* value);
  void add_cluster_ids(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& cluster_ids() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_cluster_ids();
  private:
  const std::string& _internal_cluster_ids(int index) const;
  std::string* _internal_add_cluster_ids();
  public:

  // string session_id = 1;
  void clear_session_id();
  const std::string& session_id() const;
  void set_session_id(const std::string& value);
  void set_session_id(std::string&& value);
  void set_session_id(const char* value);
  void set_session_id(const char* value, size_t size);
  std::string* mutable_session_id();
  std::string* release_session_id();
  void set_allocated_session_id(std::string* session_id);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_session_id();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_session_id(
      std::string* session_id);
  private:
  const std::string& _internal_session_id() const;
  void _internal_set_session_id(const std::string& value);
  std::string* _internal_mutable_session_id();
  public:

  // bytes ct_q = 3;
  void clear_ct_q();
  const std::string& ct_q() const;
  void set_ct_q(const std::string& value);
  void set_ct_q(std::string&& value);
  void set_ct_q(const char* value);
  void set_ct_q(const void* value, size_t size);
  std::string* mutable_ct_q();
  std::string* release_ct_q();
  void set_allocated_ct_q(std::string* ct_q);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_ct_q();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_ct_q(
      std::string* ct_q);
  private:
  const std::string& _internal_ct_q() const;
  void _internal_set_ct_q(const std::string& value);
  std::string* _internal_mutable_ct_q();
  public:

  // string key_ver = 4;
  void clear_key_ver();
  const std::string& key_ver() const;
  void set_key_ver(const std::string& value);
  void set_key_ver(std::string&& value);
  void set_key_ver(const char* value);
  void set_key_ver(const char* value, size_t size);
  std::string* mutable_key_ver();
  std::string* release_key_ver();
  void set_allocated_key_ver(std::string* key_ver);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_key_ver();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_key_ver(
      std::string* key_ver);
  private:
  const std::string& _internal_key_ver() const;
  void _internal_set_key_ver(const std::string& value);
  std::string* _internal_mutable_key_ver();
  public:

  // string fake_policy = 5;
  void clear_fake_policy();
  const std::string& fake_policy() const;
  void set_fake_policy(const std::string& value);
  void set_fake_policy(std::string&& value);
  void set_fake_policy(const char* value);
  void set_fake_policy(const char* value, size_t size);
  std::string* mutable_fake_policy();
  std::string* release_fake_policy();
  void set_allocated_fake_policy(std::string* fake_policy);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_fake_policy();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_fake_policy(
      std::string* fake_policy);
  private:
  const std::string& _internal_fake_policy() const;
  void _internal_set_fake_policy(const std::string& value);
  std::string* _internal_mutable_fake_policy();
  public:

  // uint64 scale = 6;
  void clear_scale();
  ::PROTOBUF_NAMESPACE_ID::uint64 scale() const;
  void set_scale(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_scale() const;
  void _internal_set_scale(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint32 topR = 7;
  void clear_topr();
  ::PROTOBUF_NAMESPACE_ID::uint32 topr() const;
  void set_topr(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_topr() const;
  void _internal_set_topr(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:gateway.v1.SearchRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> cluster_ids_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr session_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr ct_q_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr key_ver_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr fake_policy_;
  ::PROTOBUF_NAMESPACE_ID::uint64 scale_;
  ::PROTOBUF_NAMESPACE_ID::uint32 topr_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_gateway_2eproto;
};
// -------------------------------------------------------------------

class PackShape PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:gateway.v1.PackShape) */ {
 public:
  inline PackShape() : PackShape(nullptr) {};
  virtual ~PackShape();

  PackShape(const PackShape& from);
  PackShape(PackShape&& from) noexcept
    : PackShape() {
    *this = ::std::move(from);
  }

  inline PackShape& operator=(const PackShape& from) {
    CopyFrom(from);
    return *this;
  }
  inline PackShape& operator=(PackShape&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PackShape& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PackShape* internal_default_instance() {
    return reinterpret_cast<const PackShape*>(
               &_PackShape_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PackShape& a, PackShape& b) {
    a.Swap(&b);
  }
  inline void Swap(PackShape* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PackShape* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PackShape* New() const final {
    return CreateMaybeMessage<PackShape>(nullptr);
  }

  PackShape* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PackShape>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PackShape& from);
  void MergeFrom(const PackShape& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PackShape* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "gateway.v1.PackShape";
  }
  protected:
  explicit PackShape(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_gateway_2eproto);
    return ::descriptor_table_gateway_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBatchFieldNumber = 1,
    kSlotsFieldNumber = 2,
  };
  // uint32 batch = 1;
  void clear_batch();
  ::PROTOBUF_NAMESPACE_ID::uint32 batch() const;
  void set_batch(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_batch() const;
  void _internal_set_batch(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 slots = 2;
  void clear_slots();
  ::PROTOBUF_NAMESPACE_ID::uint32 slots() const;
  void set_slots(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_slots() const;
  void _internal_set_slots(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:gateway.v1.PackShape)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint32 batch_;
  ::PROTOBUF_NAMESPACE_ID::uint32 slots_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_gateway_2eproto;
};
// -------------------------------------------------------------------

class SearchResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:gateway.v1.SearchResponse) */ {
 public:
  inline SearchResponse() : SearchResponse(nullptr) {};
  virtual ~SearchResponse();

  SearchResponse(const SearchResponse& from);
  SearchResponse(SearchResponse&& from) noexcept
    : SearchResponse() {
    *this = ::std::move(from);
  }

  inline SearchResponse& operator=(const SearchResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline SearchResponse& operator=(SearchResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SearchResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SearchResponse* internal_default_instance() {
    return reinterpret_cast<const SearchResponse*>(
               &_SearchResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(SearchResponse& a, SearchResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(SearchResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SearchResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline SearchResponse* New() const final {
    return CreateMaybeMessage<SearchResponse>(nullptr);
  }

  SearchResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SearchResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SearchResponse& from);
  void MergeFrom(const SearchResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SearchResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "gateway.v1.SearchResponse";
  }
  protected:
  explicit SearchResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_gateway_2eproto);
    return ::descriptor_table_gateway_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kScoresCiphertextsFieldNumber = 1,
    kPackShapesFieldNumber = 2,
    kLatencyMsFieldNumber = 3,
  };
  // repeated bytes scores_ciphertexts = 1;
  int scores_ciphertexts_size() const;
  private:
  int _internal_scores_ciphertexts_size() const;
  public:
  void clear_scores_ciphertexts();
  const std::string& scores_ciphertexts(int index) const;
  std::string* mutable_scores_ciphertexts(int index);
  void set_scores_ciphertexts(int index, const std::string& value);
  void set_scores_ciphertexts(int index, std::string&& value);
  void set_scores_ciphertexts(int index, const char* value);
  void set_scores_ciphertexts(int index, const void* value, size_t size);
  std::string* add_scores_ciphertexts();
  void add_scores_ciphertexts(const std::string& value);
  void add_scores_ciphertexts(std::string&& value);
  void add_scores_ciphertexts(const char* value);
  void add_scores_ciphertexts(const void* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& scores_ciphertexts() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_scores_ciphertexts();
  private:
  const std::string& _internal_scores_ciphertexts(int index) const;
  std::string* _internal_add_scores_ciphertexts();
  public:

  // repeated .gateway.v1.PackShape pack_shapes = 2;
  int pack_shapes_size() const;
  private:
  int _internal_pack_shapes_size() const;
  public:
  void clear_pack_shapes();
  ::gateway::v1::PackShape* mutable_pack_shapes(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gateway::v1::PackShape >*
      mutable_pack_shapes();
  private:
  const ::gateway::v1::PackShape& _internal_pack_shapes(int index) const;
  ::gateway::v1::PackShape* _internal_add_pack_shapes();
  public:
  const ::gateway::v1::PackShape& pack_shapes(int index) const;
  ::gateway::v1::PackShape* add_pack_shapes();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gateway::v1::PackShape >&
      pack_shapes() const;

  // uint32 latency_ms = 3;
  void clear_latency_ms();
  ::PROTOBUF_NAMESPACE_ID::uint32 latency_ms() const;
  void set_latency_ms(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_latency_ms() const;
  void _internal_set_latency_ms(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:gateway.v1.SearchResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> scores_ciphertexts_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gateway::v1::PackShape > pack_shapes_;
  ::PROTOBUF_NAMESPACE_ID::uint32 latency_ms_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_gateway_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SearchRequest

// string session_id = 1;
inline void SearchRequest::clear_session_id() {
  session_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& SearchRequest::session_id() const {
  // @@protoc_insertion_point(field_get:gateway.v1.SearchRequest.session_id)
  return _internal_session_id();
}
inline void SearchRequest::set_session_id(const std::string& value) {
  _internal_set_session_id(value);
  // @@protoc_insertion_point(field_set:gateway.v1.SearchRequest.session_id)
}
inline std::string* SearchRequest::mutable_session_id() {
  // @@protoc_insertion_point(field_mutable:gateway.v1.SearchRequest.session_id)
  return _internal_mutable_session_id();
}
inline const std::string& SearchRequest::_internal_session_id() const {
  return session_id_.Get();
}
inline void SearchRequest::_internal_set_session_id(const std::string& value) {
  
  session_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void SearchRequest::set_session_id(std::string&& value) {
  
  session_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:gateway.v1.SearchRequest.session_id)
}
inline void SearchRequest::set_session_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  session_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:gateway.v1.SearchRequest.session_id)
}
inline void SearchRequest::set_session_id(const char* value,
    size_t size) {
  
  session_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:gateway.v1.SearchRequest.session_id)
}
inline std::string* SearchRequest::_internal_mutable_session_id() {
  
  return session_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* SearchRequest::release_session_id() {
  // @@protoc_insertion_point(field_release:gateway.v1.SearchRequest.session_id)
  return session_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void SearchRequest::set_allocated_session_id(std::string* session_id) {
  if (session_id != nullptr) {
    
  } else {
    
  }
  session_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), session_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:gateway.v1.SearchRequest.session_id)
}
inline std::string* SearchRequest::unsafe_arena_release_session_id() {
  // @@protoc_insertion_point(field_unsafe_arena_release:gateway.v1.SearchRequest.session_id)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return session_id_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void SearchRequest::unsafe_arena_set_allocated_session_id(
    std::string* session_id) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (session_id != nullptr) {
    
  } else {
    
  }
  session_id_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      session_id, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:gateway.v1.SearchRequest.session_id)
}

// repeated string cluster_ids = 2;
inline int SearchRequest::_internal_cluster_ids_size() const {
  return cluster_ids_.size();
}
inline int SearchRequest::cluster_ids_size() const {
  return _internal_cluster_ids_size();
}
inline void SearchRequest::clear_cluster_ids() {
  cluster_ids_.Clear();
}
inline std::string* SearchRequest::add_cluster_ids() {
  // @@protoc_insertion_point(field_add_mutable:gateway.v1.SearchRequest.cluster_ids)
  return _internal_add_cluster_ids();
}
inline const std::string& SearchRequest::_internal_cluster_ids(int index) const {
  return cluster_ids_.Get(index);
}
inline const std::string& SearchRequest::cluster_ids(int index) const {
  // @@protoc_insertion_point(field_get:gateway.v1.SearchRequest.cluster_ids)
  return _internal_cluster_ids(index);
}
inline std::string* SearchRequest::mutable_cluster_ids(int index) {
  // @@protoc_insertion_point(field_mutable:gateway.v1.SearchRequest.cluster_ids)
  return cluster_ids_.Mutable(index);
}
inline void SearchRequest::set_cluster_ids(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:gateway.v1.SearchRequest.cluster_ids)
  cluster_ids_.Mutable(index)->assign(value);
}
inline void SearchRequest::set_cluster_ids(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:gateway.v1.SearchRequest.cluster_ids)
  cluster_ids_.Mutable(index)->assign(std::move(value));
}
inline void SearchRequest::set_cluster_ids(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  cluster_ids_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:gateway.v1.SearchRequest.cluster_ids)
}
inline void SearchRequest::set_cluster_ids(int index, const char* value, size_t size) {
  cluster_ids_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:gateway.v1.SearchRequest.cluster_ids)
}
inline std::string* SearchRequest::_internal_add_cluster_ids() {
  return cluster_ids_.Add();
}
inline void SearchRequest::add_cluster_ids(const std::string& value) {
  cluster_ids_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:gateway.v1.SearchRequest.cluster_ids)
}
inline void SearchRequest::add_cluster_ids(std::string&& value) {
  cluster_ids_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:gateway.v1.SearchRequest.cluster_ids)
}
inline void SearchRequest::add_cluster_ids(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  cluster_ids_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:gateway.v1.SearchRequest.cluster_ids)
}
inline void SearchRequest::add_cluster_ids(const char* value, size_t size) {
  cluster_ids_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:gateway.v1.SearchRequest.cluster_ids)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
SearchRequest::cluster_ids() const {
  // @@protoc_insertion_point(field_list:gateway.v1.SearchRequest.cluster_ids)
  return cluster_ids_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
SearchRequest::mutable_cluster_ids() {
  // @@protoc_insertion_point(field_mutable_list:gateway.v1.SearchRequest.cluster_ids)
  return &cluster_ids_;
}

// bytes ct_q = 3;
inline void SearchRequest::clear_ct_q() {
  ct_q_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& SearchRequest::ct_q() const {
  // @@protoc_insertion_point(field_get:gateway.v1.SearchRequest.ct_q)
  return _internal_ct_q();
}
inline void SearchRequest::set_ct_q(const std::string& value) {
  _internal_set_ct_q(value);
  // @@protoc_insertion_point(field_set:gateway.v1.SearchRequest.ct_q)
}
inline std::string* SearchRequest::mutable_ct_q() {
  // @@protoc_insertion_point(field_mutable:gateway.v1.SearchRequest.ct_q)
  return _internal_mutable_ct_q();
}
inline const std::string& SearchRequest::_internal_ct_q() const {
  return ct_q_.Get();
}
inline void SearchRequest::_internal_set_ct_q(const std::string& value) {
  
  ct_q_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void SearchRequest::set_ct_q(std::string&& value) {
  
  ct_q_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:gateway.v1.SearchRequest.ct_q)
}
inline void SearchRequest::set_ct_q(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  ct_q_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:gateway.v1.SearchRequest.ct_q)
}
inline void SearchRequest::set_ct_q(const void* value,
    size_t size) {
  
  ct_q_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:gateway.v1.SearchRequest.ct_q)
}
inline std::string* SearchRequest::_internal_mutable_ct_q() {
  
  return ct_q_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* SearchRequest::release_ct_q() {
  // @@protoc_insertion_point(field_release:gateway.v1.SearchRequest.ct_q)
  return ct_q_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void SearchRequest::set_allocated_ct_q(std::string* ct_q) {
  if (ct_q != nullptr) {
    
  } else {
    
  }
  ct_q_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ct_q,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:gateway.v1.SearchRequest.ct_q)
}
inline std::string* SearchRequest::unsafe_arena_release_ct_q() {
  // @@protoc_insertion_point(field_unsafe_arena_release:gateway.v1.SearchRequest.ct_q)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return ct_q_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void SearchRequest::unsafe_arena_set_allocated_ct_q(
    std::string* ct_q) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (ct_q != nullptr) {
    
  } else {
    
  }
  ct_q_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ct_q, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:gateway.v1.SearchRequest.ct_q)
}

// string key_ver = 4;
inline void SearchRequest::clear_key_ver() {
  key_ver_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& SearchRequest::key_ver() const {
  // @@protoc_insertion_point(field_get:gateway.v1.SearchRequest.key_ver)
  return _internal_key_ver();
}
inline void SearchRequest::set_key_ver(const std::string& value) {
  _internal_set_key_ver(value);
  // @@protoc_insertion_point(field_set:gateway.v1.SearchRequest.key_ver)
}
inline std::string* SearchRequest::mutable_key_ver() {
  // @@protoc_insertion_point(field_mutable:gateway.v1.SearchRequest.key_ver)
  return _internal_mutable_key_ver();
}
inline const std::string& SearchRequest::_internal_key_ver() const {
  return key_ver_.Get();
}
inline void SearchRequest::_internal_set_key_ver(const std::string& value) {
  
  key_ver_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void SearchRequest::set_key_ver(std::string&& value) {
  
  key_ver_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:gateway.v1.SearchRequest.key_ver)
}
inline void SearchRequest::set_key_ver(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  key_ver_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:gateway.v1.SearchRequest.key_ver)
}
inline void SearchRequest::set_key_ver(const char* value,
    size_t size) {
  
  key_ver_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:gateway.v1.SearchRequest.key_ver)
}
inline std::string* SearchRequest::_internal_mutable_key_ver() {
  
  return key_ver_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* SearchRequest::release_key_ver() {
  // @@protoc_insertion_point(field_release:gateway.v1.SearchRequest.key_ver)
  return key_ver_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void SearchRequest::set_allocated_key_ver(std::string* key_ver) {
  if (key_ver != nullptr) {
    
  } else {
    
  }
  key_ver_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), key_ver,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:gateway.v1.SearchRequest.key_ver)
}
inline std::string* SearchRequest::unsafe_arena_release_key_ver() {
  // @@protoc_insertion_point(field_unsafe_arena_release:gateway.v1.SearchRequest.key_ver)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return key_ver_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void SearchRequest::unsafe_arena_set_allocated_key_ver(
    std::string* key_ver) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (key_ver != nullptr) {
    
  } else {
    
  }
  key_ver_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      key_ver, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:gateway.v1.SearchRequest.key_ver)
}

// string fake_policy = 5;
inline void SearchRequest::clear_fake_policy() {
  fake_policy_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& SearchRequest::fake_policy() const {
  // @@protoc_insertion_point(field_get:gateway.v1.SearchRequest.fake_policy)
  return _internal_fake_policy();
}
inline void SearchRequest::set_fake_policy(const std::string& value) {
  _internal_set_fake_policy(value);
  // @@protoc_insertion_point(field_set:gateway.v1.SearchRequest.fake_policy)
}
inline std::string* SearchRequest::mutable_fake_policy() {
  // @@protoc_insertion_point(field_mutable:gateway.v1.SearchRequest.fake_policy)
  return _internal_mutable_fake_policy();
}
inline const std::string& SearchRequest::_internal_fake_policy() const {
  return fake_policy_.Get();
}
inline void SearchRequest::_internal_set_fake_policy(const std::string& value) {
  
  fake_policy_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void SearchRequest::set_fake_policy(std::string&& value) {
  
  fake_policy_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:gateway.v1.SearchRequest.fake_policy)
}
inline void SearchRequest::set_fake_policy(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  fake_policy_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:gateway.v1.SearchRequest.fake_policy)
}
inline void SearchRequest::set_fake_policy(const char* value,
    size_t size) {
  
  fake_policy_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:gateway.v1.SearchRequest.fake_policy)
}
inline std::string* SearchRequest::_internal_mutable_fake_policy() {
  
  return fake_policy_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* SearchRequest::release_fake_policy() {
  // @@protoc_insertion_point(field_release:gateway.v1.SearchRequest.fake_policy)
  return fake_policy_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void SearchRequest::set_allocated_fake_policy(std::string* fake_policy) {
  if (fake_policy != nullptr) {
    
  } else {
    
  }
  fake_policy_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), fake_policy,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:gateway.v1.SearchRequest.fake_policy)
}
inline std::string* SearchRequest::unsafe_arena_release_fake_policy() {
  // @@protoc_insertion_point(field_unsafe_arena_release:gateway.v1.SearchRequest.fake_policy)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return fake_policy_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void SearchRequest::unsafe_arena_set_allocated_fake_policy(
    std::string* fake_policy) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (fake_policy != nullptr) {
    
  } else {
    
  }
  fake_policy_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      fake_policy, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:gateway.v1.SearchRequest.fake_policy)
}

// uint64 scale = 6;
inline void SearchRequest::clear_scale() {
  scale_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 SearchRequest::_internal_scale() const {
  return scale_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 SearchRequest::scale() const {
  // @@protoc_insertion_point(field_get:gateway.v1.SearchRequest.scale)
  return _internal_scale();
}
inline void SearchRequest::_internal_set_scale(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  scale_ = value;
}
inline void SearchRequest::set_scale(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_scale(value);
  // @@protoc_insertion_point(field_set:gateway.v1.SearchRequest.scale)
}

// uint32 topR = 7;
inline void SearchRequest::clear_topr() {
  topr_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SearchRequest::_internal_topr() const {
  return topr_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SearchRequest::topr() const {
  // @@protoc_insertion_point(field_get:gateway.v1.SearchRequest.topR)
  return _internal_topr();
}
inline void SearchRequest::_internal_set_topr(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  topr_ = value;
}
inline void SearchRequest::set_topr(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_topr(value);
  // @@protoc_insertion_point(field_set:gateway.v1.SearchRequest.topR)
}

// -------------------------------------------------------------------

// PackShape

// uint32 batch = 1;
inline void PackShape::clear_batch() {
  batch_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PackShape::_internal_batch() const {
  return batch_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PackShape::batch() const {
  // @@protoc_insertion_point(field_get:gateway.v1.PackShape.batch)
  return _internal_batch();
}
inline void PackShape::_internal_set_batch(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  batch_ = value;
}
inline void PackShape::set_batch(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_batch(value);
  // @@protoc_insertion_point(field_set:gateway.v1.PackShape.batch)
}

// uint32 slots = 2;
inline void PackShape::clear_slots() {
  slots_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PackShape::_internal_slots() const {
  return slots_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PackShape::slots() const {
  // @@protoc_insertion_point(field_get:gateway.v1.PackShape.slots)
  return _internal_slots();
}
inline void PackShape::_internal_set_slots(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  slots_ = value;
}
inline void PackShape::set_slots(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_slots(value);
  // @@protoc_insertion_point(field_set:gateway.v1.PackShape.slots)
}

// -------------------------------------------------------------------

// SearchResponse

// repeated bytes scores_ciphertexts = 1;
inline int SearchResponse::_internal_scores_ciphertexts_size() const {
  return scores_ciphertexts_.size();
}
inline int SearchResponse::scores_ciphertexts_size() const {
  return _internal_scores_ciphertexts_size();
}
inline void SearchResponse::clear_scores_ciphertexts() {
  scores_ciphertexts_.Clear();
}
inline std::string* SearchResponse::add_scores_ciphertexts() {
  // @@protoc_insertion_point(field_add_mutable:gateway.v1.SearchResponse.scores_ciphertexts)
  return _internal_add_scores_ciphertexts();
}
inline const std::string& SearchResponse::_internal_scores_ciphertexts(int index) const {
  return scores_ciphertexts_.Get(index);
}
inline const std::string& SearchResponse::scores_ciphertexts(int index) const {
  // @@protoc_insertion_point(field_get:gateway.v1.SearchResponse.scores_ciphertexts)
  return _internal_scores_ciphertexts(index);
}
inline std::string* SearchResponse::mutable_scores_ciphertexts(int index) {
  // @@protoc_insertion_point(field_mutable:gateway.v1.SearchResponse.scores_ciphertexts)
  return scores_ciphertexts_.Mutable(index);
}
inline void SearchResponse::set_scores_ciphertexts(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:gateway.v1.SearchResponse.scores_ciphertexts)
  scores_ciphertexts_.Mutable(index)->assign(value);
}
inline void SearchResponse::set_scores_ciphertexts(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:gateway.v1.SearchResponse.scores_ciphertexts)
  scores_ciphertexts_.Mutable(index)->assign(std::move(value));
}
inline void SearchResponse::set_scores_ciphertexts(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  scores_ciphertexts_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:gateway.v1.SearchResponse.scores_ciphertexts)
}
inline void SearchResponse::set_scores_ciphertexts(int index, const void* value, size_t size) {
  scores_ciphertexts_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:gateway.v1.SearchResponse.scores_ciphertexts)
}
inline std::string* SearchResponse::_internal_add_scores_ciphertexts() {
  return scores_ciphertexts_.Add();
}
inline void SearchResponse::add_scores_ciphertexts(const std::string& value) {
  scores_ciphertexts_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:gateway.v1.SearchResponse.scores_ciphertexts)
}
inline void SearchResponse::add_scores_ciphertexts(std::string&& value) {
  scores_ciphertexts_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:gateway.v1.SearchResponse.scores_ciphertexts)
}
inline void SearchResponse::add_scores_ciphertexts(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  scores_ciphertexts_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:gateway.v1.SearchResponse.scores_ciphertexts)
}
inline void SearchResponse::add_scores_ciphertexts(const void* value, size_t size) {
  scores_ciphertexts_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:gateway.v1.SearchResponse.scores_ciphertexts)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
SearchResponse::scores_ciphertexts() const {
  // @@protoc_insertion_point(field_list:gateway.v1.SearchResponse.scores_ciphertexts)
  return scores_ciphertexts_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
SearchResponse::mutable_scores_ciphertexts() {
  // @@protoc_insertion_point(field_mutable_list:gateway.v1.SearchResponse.scores_ciphertexts)
  return &scores_ciphertexts_;
}

// repeated .gateway.v1.PackShape pack_shapes = 2;
inline int SearchResponse::_internal_pack_shapes_size() const {
  return pack_shapes_.size();
}
inline int SearchResponse::pack_shapes_size() const {
  return _internal_pack_shapes_size();
}
inline void SearchResponse::clear_pack_shapes() {
  pack_shapes_.Clear();
}
inline ::gateway::v1::PackShape* SearchResponse::mutable_pack_shapes(int index) {
  // @@protoc_insertion_point(field_mutable:gateway.v1.SearchResponse.pack_shapes)
  return pack_shapes_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gateway::v1::PackShape >*
SearchResponse::mutable_pack_shapes() {
  // @@protoc_insertion_point(field_mutable_list:gateway.v1.SearchResponse.pack_shapes)
  return &pack_shapes_;
}
inline const ::gateway::v1::PackShape& SearchResponse::_internal_pack_shapes(int index) const {
  return pack_shapes_.Get(index);
}
inline const ::gateway::v1::PackShape& SearchResponse::pack_shapes(int index) const {
  // @@protoc_insertion_point(field_get:gateway.v1.SearchResponse.pack_shapes)
  return _internal_pack_shapes(index);
}
inline ::gateway::v1::PackShape* SearchResponse::_internal_add_pack_shapes() {
  return pack_shapes_.Add();
}
inline ::gateway::v1::PackShape* SearchResponse::add_pack_shapes() {
  // @@protoc_insertion_point(field_add:gateway.v1.SearchResponse.pack_shapes)
  return _internal_add_pack_shapes();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gateway::v1::PackShape >&
SearchResponse::pack_shapes() const {
  // @@protoc_insertion_point(field_list:gateway.v1.SearchResponse.pack_shapes)
  return pack_shapes_;
}

// uint32 latency_ms = 3;
inline void SearchResponse::clear_latency_ms() {
  latency_ms_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SearchResponse::_internal_latency_ms() const {
  return latency_ms_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SearchResponse::latency_ms() const {
  // @@protoc_insertion_point(field_get:gateway.v1.SearchResponse.latency_ms)
  return _internal_latency_ms();
}
inline void SearchResponse::_internal_set_latency_ms(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  latency_ms_ = value;
}
inline void SearchResponse::set_latency_ms(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_latency_ms(value);
  // @@protoc_insertion_point(field_set:gateway.v1.SearchResponse.latency_ms)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace v1
}  // namespace gateway

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_gateway_2eproto
